### ISSUE TITLE
ti dosen't work in android 

### ISSUE THREAD

**Issue by jinghun1999** [JamesWatling/react-native-list-view-select#5]
when set state visible, but it dosen't show

**Comment by jcuero** [comment]
I had the same problem. Try to overwrite container styles: containerStyle={{}}

`<ListViewSelect
                        containerStyle={{}}
                        list={items}
                        isVisible={true}
                        onClick={this.setItem}
                        onClose={this.closePopover}
                    />`

**Comment by jesouhaite08** [comment]
Thanks @jcuero, you solved my problem.
